---
- name: Setting InitD init system variables.
  set_fact:
    filebeat: "{{ filebeat | combine(initd) }}"
  when: ansible_service_mgr != 'systemd'

- name: Set Filebeat version if defined
  set_fact:
    fb_package_name: '{{ fb_package_name }}-{{ filebeat_version }}'
  when: filebeat_version.find('.x') == -1

- name: Redhat - Importing latest logstash GPG Key
  become: True
  rpm_key:
    key: '{{ elastic_gpg_key }}'
    state: present
  register: installed_key
  until: installed_key is succeeded

# - name: Checking awk version
#   command: "awk --version"
#   register: awk_installed_version
#   changed_when: False

# - name: Set awk version number
#   set_fact:
#     awk_version: '{{ awk_installed_version.stdout_lines[0][8:13] }}'

# - name: Update awk to new version
#   become: True
#   block:
#     - name: copy gawk
#       become: True
#       copy:
#         src: '{{ role_path }}/files/gawk'
#         dest: '/usr/local/bin/gawk'
#         backup: True
#         owner: root
#         group: root
#         mode: 0755

#     - name: update symlinks
#       become: True
#       file:
#         src: '/usr/local/bin/gawk'
#         dest: '/bin/awk'
#         state: link
#   when: awk_version is version_compare('4.2.1', operator='lt', strict=True)

- name: Redhat - Install elasticsearch repository
  become: True
  yum_repository:
    name: elasticsearch
    description: Elasticsearch repository
    file: '{{ es_repo_file }}'
    baseurl: '{{ es_yum_url }}'
    gpgcheck: True
    gpgkey: '{{ elastic_gpg_key }}'
    enabled: True
    state: present

- name: Redhat - Installing Filebeat package
  become: True
  yum:
    name: '{{ fb_package_name }}'
    state: present
    update_cache: True
  register: installed_package
  until: installed_package is succeeded
  notify: Restart filebeat
