---
# handlers file for filebeat

# NOTE: this action will restart ALL filebeats on the target server (it means that all chained systemd filebeat daemonscripts will be forced to restart)
- name: start_filebeat_systemd
  become: True
  systemd:
    name: "filebeat-pipeline"
    state: started
    enabled: True
    daemon-reload: yes

- name: start_filebeat_initd
  become: True
  service:
    name: "filebeat-pipeline"
    pattern: "{{ path.home }}/bin/filebeat"
    state: started
    enabled: True
