---
# handlers file for filebeat

# NOTE: this action will restart ALL filebeats on the target server.
# It means that all chained systemd filebeat daemonscripts will be forced to restart
- name: start_filebeat_systemd
  become: True
  systemd:
    name: "filebeat-pipeline"
    state: started
    enabled: True
    daemon-reload: True

- name: start_filebeat_initd
  become: True
  service:
    name: "filebeat-pipeline"
    pattern: "{{ path.home }}/bin/filebeat"
    state: started
    enabled: True

- name: Reload systemd configuration
  systemd:
    daemon_reload: True
  become: True

- name: Restart filebeat
  service:
    name: filebeat
    state: restarted
  become: True